@startuml
!include _estilo.iuml
actor "Jefe de faena" as JF
rectangle ":GestorManifiesto" as GM
rectangle ":ServicioAduana" as SA
rectangle ":Manifiesto" as M

JF -- GM : "1: importarManifiesto(nave, viaje, fecha) ↓\n↑ Manifiesto (resumen de la importación)"
GM -- SA : "1.1: descargarXML(nave, viaje, fecha) ↓\n↑ xml : String"
GM -- M : "1.2 [servicio responde y esquema válido]:\n<<create>>(nave, viaje) ↓"
GM -- GM : "1.3: agregarContenedor()\ny agregarLinea()"
@enduml
