@startuml
!include _estilo.iuml
actor "Jefe de faena" as JF
rectangle ":Sistema BeeTracer" as SB
rectangle ":ServicioAduana" as SA

JF -- SB : "1: importarManifiesto(nave, viaje) ↓\n↑ confirmación de importación"
SB -- SA : "1.1: solicitarXML() ↓\n↑ retorna XML"
SB -- SB : "1.2 [XML válido y servicio online]:\nguardarContenedoresYLotes()"
@enduml
