@startuml
!include _estilo.iuml
actor "Jefe de faena" as JF
rectangle ":Sistema BeeTracer" as SB

JF -- SB : "1: crearProgramacion(contenedor, fecha, hora) ↓\n2 [sin conflictos de agenda]:\nasignarPersonal(cuadrilla, jefeTarjador) ↓\n↑ confirmación exitosa"
SB -- SB : "1.1: verificarDisponibilidadHorario()\n2.1: verificarDisponibilidadPersonal()\n2.2: guardarProgramacion()"
@enduml
