@startuml
!include _estilo.iuml
actor "Jefe de faena" as JF
rectangle ":GestorProgramacion" as GP
rectangle ":Programacion" as P
rectangle ":Cuadrilla" as CU
rectangle ":Trabajador" as T

JF --> GP : "1: contenedores := listarContenedoresPendientes()\n2: p := crearProgramacion(…)\n3: asignarCuadrilla(…)"
GP --> GP : "2.1: conflicto := hayConflicto(…)"
GP --> P : "2.2 [sin conflicto]: <<create>>\n3.3 [ambos disponibles]:\n    asignarCuadrilla(c, jefe)"
GP --> CU : "3.1: libre := estaDisponible(…)"
GP --> T : "3.2: libre := estaDisponible(…)"
@enduml
