skinparam shadowing false
skinparam defaultFontName "DejaVu Sans"
skinparam defaultFontSize 13
skinparam sequenceMessageAlign left
skinparam responseMessageBelowArrow true
skinparam ParticipantPadding 12
skinparam BoxPadding 10
skinparam rectangle {
  BackgroundColor #ECECFF
  BorderColor #9370DB
}
skinparam actor {
  BackgroundColor #ECECFF
  BorderColor #9370DB
}
skinparam ArrowColor #333333
skinparam actorStyle stick
hide footbox
